//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZucchettiGiorLavorServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hfwe_fsendjustify.ws.localhost/", ConfigurationName="ZucchettiGiorLavorServiceReference.hfwe_fsendjustifyWS")]
    public interface hfwe_fsendjustifyWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ZucchettiGiorLavorServiceReference.hfwe_fsendjustify_RunResponse> hfwe_fsendjustify_RunAsync(ZucchettiGiorLavorServiceReference.hfwe_fsendjustify_Run request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hfwe_fsendjustify_Run
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hfwe_fsendjustify_Run", Namespace="http://hfwe_fsendjustify.ws.localhost/", Order=0)]
        public ZucchettiGiorLavorServiceReference.hfwe_fsendjustify_RunBody Body;
        
        public hfwe_fsendjustify_Run()
        {
        }
        
        public hfwe_fsendjustify_Run(ZucchettiGiorLavorServiceReference.hfwe_fsendjustify_RunBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hfwe_fsendjustify.ws.localhost/")]
    public partial class hfwe_fsendjustify_RunBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string m_UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string m_Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string m_Company;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pIdCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pIdCompany;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pIdEmploy;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string pDateStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string pDateEnd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string pTimeStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string pTimeEnd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public double pQty;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string pReason;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string pPreNot;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string pPostNot;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string pAllDay;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string pMorning;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string pAfternoon;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string pPeriodHours;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string pIdAnomaly;
        
        public hfwe_fsendjustify_RunBody()
        {
        }
        
        public hfwe_fsendjustify_RunBody(
                    string m_UserName, 
                    string m_Password, 
                    string m_Company, 
                    string pIdCode, 
                    string pIdCompany, 
                    string pIdEmploy, 
                    string pDateStart, 
                    string pDateEnd, 
                    string pTimeStart, 
                    string pTimeEnd, 
                    double pQty, 
                    string pReason, 
                    string pPreNot, 
                    string pPostNot, 
                    string pAllDay, 
                    string pMorning, 
                    string pAfternoon, 
                    string pPeriodHours, 
                    string pIdAnomaly)
        {
            this.m_UserName = m_UserName;
            this.m_Password = m_Password;
            this.m_Company = m_Company;
            this.pIdCode = pIdCode;
            this.pIdCompany = pIdCompany;
            this.pIdEmploy = pIdEmploy;
            this.pDateStart = pDateStart;
            this.pDateEnd = pDateEnd;
            this.pTimeStart = pTimeStart;
            this.pTimeEnd = pTimeEnd;
            this.pQty = pQty;
            this.pReason = pReason;
            this.pPreNot = pPreNot;
            this.pPostNot = pPostNot;
            this.pAllDay = pAllDay;
            this.pMorning = pMorning;
            this.pAfternoon = pAfternoon;
            this.pPeriodHours = pPeriodHours;
            this.pIdAnomaly = pIdAnomaly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hfwe_fsendjustify_RunResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hfwe_fsendjustify_RunResponse", Namespace="http://hfwe_fsendjustify.ws.localhost/", Order=0)]
        public ZucchettiGiorLavorServiceReference.hfwe_fsendjustify_RunResponseBody Body;
        
        public hfwe_fsendjustify_RunResponse()
        {
        }
        
        public hfwe_fsendjustify_RunResponse(ZucchettiGiorLavorServiceReference.hfwe_fsendjustify_RunResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hfwe_fsendjustify.ws.localhost/")]
    public partial class hfwe_fsendjustify_RunResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public hfwe_fsendjustify_RunResponseBody()
        {
        }
        
        public hfwe_fsendjustify_RunResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface hfwe_fsendjustifyWSChannel : ZucchettiGiorLavorServiceReference.hfwe_fsendjustifyWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class hfwe_fsendjustifyWSClient : System.ServiceModel.ClientBase<ZucchettiGiorLavorServiceReference.hfwe_fsendjustifyWS>, ZucchettiGiorLavorServiceReference.hfwe_fsendjustifyWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public hfwe_fsendjustifyWSClient() : 
                base(hfwe_fsendjustifyWSClient.GetDefaultBinding(), hfwe_fsendjustifyWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.hfwe_fsendjustifyWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public hfwe_fsendjustifyWSClient(EndpointConfiguration endpointConfiguration) : 
                base(hfwe_fsendjustifyWSClient.GetBindingForEndpoint(endpointConfiguration), hfwe_fsendjustifyWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public hfwe_fsendjustifyWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(hfwe_fsendjustifyWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public hfwe_fsendjustifyWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(hfwe_fsendjustifyWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public hfwe_fsendjustifyWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZucchettiGiorLavorServiceReference.hfwe_fsendjustify_RunResponse> ZucchettiGiorLavorServiceReference.hfwe_fsendjustifyWS.hfwe_fsendjustify_RunAsync(ZucchettiGiorLavorServiceReference.hfwe_fsendjustify_Run request)
        {
            return base.Channel.hfwe_fsendjustify_RunAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZucchettiGiorLavorServiceReference.hfwe_fsendjustify_RunResponse> hfwe_fsendjustify_RunAsync(
                    string m_UserName, 
                    string m_Password, 
                    string m_Company, 
                    string pIdCode, 
                    string pIdCompany, 
                    string pIdEmploy, 
                    string pDateStart, 
                    string pDateEnd, 
                    string pTimeStart, 
                    string pTimeEnd, 
                    double pQty, 
                    string pReason, 
                    string pPreNot, 
                    string pPostNot, 
                    string pAllDay, 
                    string pMorning, 
                    string pAfternoon, 
                    string pPeriodHours, 
                    string pIdAnomaly)
        {
            ZucchettiGiorLavorServiceReference.hfwe_fsendjustify_Run inValue = new ZucchettiGiorLavorServiceReference.hfwe_fsendjustify_Run();
            inValue.Body = new ZucchettiGiorLavorServiceReference.hfwe_fsendjustify_RunBody();
            inValue.Body.m_UserName = m_UserName;
            inValue.Body.m_Password = m_Password;
            inValue.Body.m_Company = m_Company;
            inValue.Body.pIdCode = pIdCode;
            inValue.Body.pIdCompany = pIdCompany;
            inValue.Body.pIdEmploy = pIdEmploy;
            inValue.Body.pDateStart = pDateStart;
            inValue.Body.pDateEnd = pDateEnd;
            inValue.Body.pTimeStart = pTimeStart;
            inValue.Body.pTimeEnd = pTimeEnd;
            inValue.Body.pQty = pQty;
            inValue.Body.pReason = pReason;
            inValue.Body.pPreNot = pPreNot;
            inValue.Body.pPostNot = pPostNot;
            inValue.Body.pAllDay = pAllDay;
            inValue.Body.pMorning = pMorning;
            inValue.Body.pAfternoon = pAfternoon;
            inValue.Body.pPeriodHours = pPeriodHours;
            inValue.Body.pIdAnomaly = pIdAnomaly;
            return ((ZucchettiGiorLavorServiceReference.hfwe_fsendjustifyWS)(this)).hfwe_fsendjustify_RunAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.hfwe_fsendjustifyWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.hfwe_fsendjustifyWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://10.16.187.58/workflow/servlet/hfwe_fsendjustify");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return hfwe_fsendjustifyWSClient.GetBindingForEndpoint(EndpointConfiguration.hfwe_fsendjustifyWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return hfwe_fsendjustifyWSClient.GetEndpointAddress(EndpointConfiguration.hfwe_fsendjustifyWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            hfwe_fsendjustifyWSPort,
        }
    }
}
