//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZucchettiRelazioneAttivita
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://htht_fwsztsrelstruct.ws.localhost/", ConfigurationName="ZucchettiRelazioneAttivita.htht_fwsztsrelstructWS")]
    public interface htht_fwsztsrelstructWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ZucchettiRelazioneAttivita.htht_fwsztsrelstruct_RunResponse> htht_fwsztsrelstruct_RunAsync(ZucchettiRelazioneAttivita.htht_fwsztsrelstruct_Run request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class htht_fwsztsrelstruct_Run
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="htht_fwsztsrelstruct_Run", Namespace="http://htht_fwsztsrelstruct.ws.localhost/", Order=0)]
        public ZucchettiRelazioneAttivita.htht_fwsztsrelstruct_RunBody Body;
        
        public htht_fwsztsrelstruct_Run()
        {
        }
        
        public htht_fwsztsrelstruct_Run(ZucchettiRelazioneAttivita.htht_fwsztsrelstruct_RunBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://htht_fwsztsrelstruct.ws.localhost/")]
    public partial class htht_fwsztsrelstruct_RunBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string m_UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string m_Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string m_Company;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string p_info;
        
        public htht_fwsztsrelstruct_RunBody()
        {
        }
        
        public htht_fwsztsrelstruct_RunBody(string m_UserName, string m_Password, string m_Company, string p_info)
        {
            this.m_UserName = m_UserName;
            this.m_Password = m_Password;
            this.m_Company = m_Company;
            this.p_info = p_info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class htht_fwsztsrelstruct_RunResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="htht_fwsztsrelstruct_RunResponse", Namespace="http://htht_fwsztsrelstruct.ws.localhost/", Order=0)]
        public ZucchettiRelazioneAttivita.htht_fwsztsrelstruct_RunResponseBody Body;
        
        public htht_fwsztsrelstruct_RunResponse()
        {
        }
        
        public htht_fwsztsrelstruct_RunResponse(ZucchettiRelazioneAttivita.htht_fwsztsrelstruct_RunResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://htht_fwsztsrelstruct.ws.localhost/")]
    public partial class htht_fwsztsrelstruct_RunResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public htht_fwsztsrelstruct_RunResponseBody()
        {
        }
        
        public htht_fwsztsrelstruct_RunResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface htht_fwsztsrelstructWSChannel : ZucchettiRelazioneAttivita.htht_fwsztsrelstructWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class htht_fwsztsrelstructWSClient : System.ServiceModel.ClientBase<ZucchettiRelazioneAttivita.htht_fwsztsrelstructWS>, ZucchettiRelazioneAttivita.htht_fwsztsrelstructWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public htht_fwsztsrelstructWSClient() : 
                base(htht_fwsztsrelstructWSClient.GetDefaultBinding(), htht_fwsztsrelstructWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.htht_fwsztsrelstructWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public htht_fwsztsrelstructWSClient(EndpointConfiguration endpointConfiguration) : 
                base(htht_fwsztsrelstructWSClient.GetBindingForEndpoint(endpointConfiguration), htht_fwsztsrelstructWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public htht_fwsztsrelstructWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(htht_fwsztsrelstructWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public htht_fwsztsrelstructWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(htht_fwsztsrelstructWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public htht_fwsztsrelstructWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZucchettiRelazioneAttivita.htht_fwsztsrelstruct_RunResponse> ZucchettiRelazioneAttivita.htht_fwsztsrelstructWS.htht_fwsztsrelstruct_RunAsync(ZucchettiRelazioneAttivita.htht_fwsztsrelstruct_Run request)
        {
            return base.Channel.htht_fwsztsrelstruct_RunAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZucchettiRelazioneAttivita.htht_fwsztsrelstruct_RunResponse> htht_fwsztsrelstruct_RunAsync(string m_UserName, string m_Password, string m_Company, string p_info)
        {
            ZucchettiRelazioneAttivita.htht_fwsztsrelstruct_Run inValue = new ZucchettiRelazioneAttivita.htht_fwsztsrelstruct_Run();
            inValue.Body = new ZucchettiRelazioneAttivita.htht_fwsztsrelstruct_RunBody();
            inValue.Body.m_UserName = m_UserName;
            inValue.Body.m_Password = m_Password;
            inValue.Body.m_Company = m_Company;
            inValue.Body.p_info = p_info;
            return ((ZucchettiRelazioneAttivita.htht_fwsztsrelstructWS)(this)).htht_fwsztsrelstruct_RunAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.htht_fwsztsrelstructWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.htht_fwsztsrelstructWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://10.16.187.59/ZTimesheet/servlet/htht_fwsztsrelstruct");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return htht_fwsztsrelstructWSClient.GetBindingForEndpoint(EndpointConfiguration.htht_fwsztsrelstructWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return htht_fwsztsrelstructWSClient.GetEndpointAddress(EndpointConfiguration.htht_fwsztsrelstructWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            htht_fwsztsrelstructWSPort,
        }
    }
}
