//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZucchettiGetGiorServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ws_vqr_hrw_codici_richieste_TabularQueryResponseTable", Namespace="http://ws_vqr_hrw_codici_richieste.ws.localhost/", ItemName="item")]
    public class ws_vqr_hrw_codici_richieste_TabularQueryResponseTable : System.Collections.Generic.List<ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_TabularQueryResponseStructure>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ws_vqr_hrw_codici_richieste_TabularQueryResponseStructure", Namespace="http://ws_vqr_hrw_codici_richieste.ws.localhost/")]
    public partial class ws_vqr_hrw_codici_richieste_TabularQueryResponseStructure : object
    {
        
        private string ANEMAILField;
        
        private string IDCOMPANYField;
        
        private string IDEMPLOYField;
        
        private double CODRICHIEField;
        
        private string CODGIUSTField;
        
        private string DADATAField;
        
        private string ADATAField;
        
        private string TPORIGINField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ANEMAIL
        {
            get
            {
                return this.ANEMAILField;
            }
            set
            {
                this.ANEMAILField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IDCOMPANY
        {
            get
            {
                return this.IDCOMPANYField;
            }
            set
            {
                this.IDCOMPANYField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IDEMPLOY
        {
            get
            {
                return this.IDEMPLOYField;
            }
            set
            {
                this.IDEMPLOYField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double CODRICHIE
        {
            get
            {
                return this.CODRICHIEField;
            }
            set
            {
                this.CODRICHIEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CODGIUST
        {
            get
            {
                return this.CODGIUSTField;
            }
            set
            {
                this.CODGIUSTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DADATA
        {
            get
            {
                return this.DADATAField;
            }
            set
            {
                this.DADATAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ADATA
        {
            get
            {
                return this.ADATAField;
            }
            set
            {
                this.ADATAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TPORIGIN
        {
            get
            {
                return this.TPORIGINField;
            }
            set
            {
                this.TPORIGINField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws_vqr_hrw_codici_richieste.ws.localhost/", ConfigurationName="ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richiesteWS")]
    public interface ws_vqr_hrw_codici_richiesteWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_QueryResponse> ws_vqr_hrw_codici_richieste_QueryAsync(ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_Query request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_TabularQueryResponse> ws_vqr_hrw_codici_richieste_TabularQueryAsync(ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_TabularQuery request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ws_vqr_hrw_codici_richieste_Query
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ws_vqr_hrw_codici_richieste_Query", Namespace="http://ws_vqr_hrw_codici_richieste.ws.localhost/", Order=0)]
        public ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_QueryBody Body;
        
        public ws_vqr_hrw_codici_richieste_Query()
        {
        }
        
        public ws_vqr_hrw_codici_richieste_Query(ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_QueryBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_vqr_hrw_codici_richieste.ws.localhost/")]
    public partial class ws_vqr_hrw_codici_richieste_QueryBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string m_UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string m_Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string m_Company;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pANEMAIL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pCODGIUST;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pDADATA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string pADATA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool m_bCount;
        
        public ws_vqr_hrw_codici_richieste_QueryBody()
        {
        }
        
        public ws_vqr_hrw_codici_richieste_QueryBody(string m_UserName, string m_Password, string m_Company, string pANEMAIL, string pCODGIUST, string pDADATA, string pADATA, bool m_bCount)
        {
            this.m_UserName = m_UserName;
            this.m_Password = m_Password;
            this.m_Company = m_Company;
            this.pANEMAIL = pANEMAIL;
            this.pCODGIUST = pCODGIUST;
            this.pDADATA = pDADATA;
            this.pADATA = pADATA;
            this.m_bCount = m_bCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ws_vqr_hrw_codici_richieste_QueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ws_vqr_hrw_codici_richieste_QueryResponse", Namespace="http://ws_vqr_hrw_codici_richieste.ws.localhost/", Order=0)]
        public ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_QueryResponseBody Body;
        
        public ws_vqr_hrw_codici_richieste_QueryResponse()
        {
        }
        
        public ws_vqr_hrw_codici_richieste_QueryResponse(ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_QueryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_vqr_hrw_codici_richieste.ws.localhost/")]
    public partial class ws_vqr_hrw_codici_richieste_QueryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ws_vqr_hrw_codici_richieste_QueryResponseBody()
        {
        }
        
        public ws_vqr_hrw_codici_richieste_QueryResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ws_vqr_hrw_codici_richieste_TabularQuery
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ws_vqr_hrw_codici_richieste_TabularQuery", Namespace="http://ws_vqr_hrw_codici_richieste.ws.localhost/", Order=0)]
        public ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_TabularQueryBody Body;
        
        public ws_vqr_hrw_codici_richieste_TabularQuery()
        {
        }
        
        public ws_vqr_hrw_codici_richieste_TabularQuery(ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_TabularQueryBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_vqr_hrw_codici_richieste.ws.localhost/")]
    public partial class ws_vqr_hrw_codici_richieste_TabularQueryBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string m_UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string m_Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string m_Company;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pANEMAIL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pCODGIUST;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pDADATA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string pADATA;
        
        public ws_vqr_hrw_codici_richieste_TabularQueryBody()
        {
        }
        
        public ws_vqr_hrw_codici_richieste_TabularQueryBody(string m_UserName, string m_Password, string m_Company, string pANEMAIL, string pCODGIUST, string pDADATA, string pADATA)
        {
            this.m_UserName = m_UserName;
            this.m_Password = m_Password;
            this.m_Company = m_Company;
            this.pANEMAIL = pANEMAIL;
            this.pCODGIUST = pCODGIUST;
            this.pDADATA = pDADATA;
            this.pADATA = pADATA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ws_vqr_hrw_codici_richieste_TabularQueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ws_vqr_hrw_codici_richieste_TabularQueryResponse", Namespace="http://ws_vqr_hrw_codici_richieste.ws.localhost/", Order=0)]
        public ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_TabularQueryResponseBody Body;
        
        public ws_vqr_hrw_codici_richieste_TabularQueryResponse()
        {
        }
        
        public ws_vqr_hrw_codici_richieste_TabularQueryResponse(ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_TabularQueryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_vqr_hrw_codici_richieste.ws.localhost/")]
    public partial class ws_vqr_hrw_codici_richieste_TabularQueryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_TabularQueryResponseTable Records;
        
        public ws_vqr_hrw_codici_richieste_TabularQueryResponseBody()
        {
        }
        
        public ws_vqr_hrw_codici_richieste_TabularQueryResponseBody(ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_TabularQueryResponseTable Records)
        {
            this.Records = Records;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ws_vqr_hrw_codici_richiesteWSChannel : ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richiesteWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ws_vqr_hrw_codici_richiesteWSClient : System.ServiceModel.ClientBase<ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richiesteWS>, ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richiesteWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ws_vqr_hrw_codici_richiesteWSClient() : 
                base(ws_vqr_hrw_codici_richiesteWSClient.GetDefaultBinding(), ws_vqr_hrw_codici_richiesteWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ws_vqr_hrw_codici_richiesteWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_vqr_hrw_codici_richiesteWSClient(EndpointConfiguration endpointConfiguration) : 
                base(ws_vqr_hrw_codici_richiesteWSClient.GetBindingForEndpoint(endpointConfiguration), ws_vqr_hrw_codici_richiesteWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_vqr_hrw_codici_richiesteWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ws_vqr_hrw_codici_richiesteWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_vqr_hrw_codici_richiesteWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ws_vqr_hrw_codici_richiesteWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_vqr_hrw_codici_richiesteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_QueryResponse> ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richiesteWS.ws_vqr_hrw_codici_richieste_QueryAsync(ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_Query request)
        {
            return base.Channel.ws_vqr_hrw_codici_richieste_QueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_QueryResponse> ws_vqr_hrw_codici_richieste_QueryAsync(string m_UserName, string m_Password, string m_Company, string pANEMAIL, string pCODGIUST, string pDADATA, string pADATA, bool m_bCount)
        {
            ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_Query inValue = new ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_Query();
            inValue.Body = new ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_QueryBody();
            inValue.Body.m_UserName = m_UserName;
            inValue.Body.m_Password = m_Password;
            inValue.Body.m_Company = m_Company;
            inValue.Body.pANEMAIL = pANEMAIL;
            inValue.Body.pCODGIUST = pCODGIUST;
            inValue.Body.pDADATA = pDADATA;
            inValue.Body.pADATA = pADATA;
            inValue.Body.m_bCount = m_bCount;
            return ((ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richiesteWS)(this)).ws_vqr_hrw_codici_richieste_QueryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_TabularQueryResponse> ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richiesteWS.ws_vqr_hrw_codici_richieste_TabularQueryAsync(ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_TabularQuery request)
        {
            return base.Channel.ws_vqr_hrw_codici_richieste_TabularQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_TabularQueryResponse> ws_vqr_hrw_codici_richieste_TabularQueryAsync(string m_UserName, string m_Password, string m_Company, string pANEMAIL, string pCODGIUST, string pDADATA, string pADATA)
        {
            ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_TabularQuery inValue = new ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_TabularQuery();
            inValue.Body = new ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richieste_TabularQueryBody();
            inValue.Body.m_UserName = m_UserName;
            inValue.Body.m_Password = m_Password;
            inValue.Body.m_Company = m_Company;
            inValue.Body.pANEMAIL = pANEMAIL;
            inValue.Body.pCODGIUST = pCODGIUST;
            inValue.Body.pDADATA = pDADATA;
            inValue.Body.pADATA = pADATA;
            return ((ZucchettiGetGiorServiceReference.ws_vqr_hrw_codici_richiesteWS)(this)).ws_vqr_hrw_codici_richieste_TabularQueryAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ws_vqr_hrw_codici_richiesteWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ws_vqr_hrw_codici_richiesteWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://gp.pcm.it/workflow/servlet/SQLDataProviderServer/ws_vqr_hrw_codici_richies" +
                        "te");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ws_vqr_hrw_codici_richiesteWSClient.GetBindingForEndpoint(EndpointConfiguration.ws_vqr_hrw_codici_richiesteWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ws_vqr_hrw_codici_richiesteWSClient.GetEndpointAddress(EndpointConfiguration.ws_vqr_hrw_codici_richiesteWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ws_vqr_hrw_codici_richiesteWSPort,
        }
    }
}
