//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZucchettiAnagServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ws_vqr_lavoroagile_TabularQueryResponseTable", Namespace="http://ws_vqr_lavoroagile.ws.localhost/", ItemName="item")]
    public class ws_vqr_lavoroagile_TabularQueryResponseTable : System.Collections.Generic.List<ZucchettiAnagServiceReference.ws_vqr_lavoroagile_TabularQueryResponseStructure>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ws_vqr_lavoroagile_TabularQueryResponseStructure", Namespace="http://ws_vqr_lavoroagile.ws.localhost/")]
    public partial class ws_vqr_lavoroagile_TabularQueryResponseStructure : object
    {
        
        private string CODICE_RAPPORTOField;
        
        private string CODICE_SOGGETTOField;
        
        private string COGNOMEField;
        
        private string NOMEField;
        
        private string CFField;
        
        private string SESSOField;
        
        private string CODICE_LUOGO_NASCITAField;
        
        private string LUOGO_NASCITAField;
        
        private string DATA_NASCITAField;
        
        private string EMAILField;
        
        private string POSIZIONE_GIURIDICAField;
        
        private string FASCIA_RETRIBUTIVAField;
        
        private string ID_DIPARTIMENTOField;
        
        private string DIPARTIMENTOField;
        
        private string ID_UFFICIOField;
        
        private string UFFICIOField;
        
        private string ID_SERVIZIOField;
        
        private string SERVIZIOField;
        
        private string ANSURNAM1Field;
        
        private string ANNAME1Field;
        
        private string ANEMAIL1Field;
        
        private string ANSURNAM2Field;
        
        private string ANNAME2Field;
        
        private string ANEMAIL2Field;
        
        private string ANSURNAM3Field;
        
        private string ANNAME3Field;
        
        private string ANEMAIL3Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CODICE_RAPPORTO
        {
            get
            {
                return this.CODICE_RAPPORTOField;
            }
            set
            {
                this.CODICE_RAPPORTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CODICE_SOGGETTO
        {
            get
            {
                return this.CODICE_SOGGETTOField;
            }
            set
            {
                this.CODICE_SOGGETTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string COGNOME
        {
            get
            {
                return this.COGNOMEField;
            }
            set
            {
                this.COGNOMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NOME
        {
            get
            {
                return this.NOMEField;
            }
            set
            {
                this.NOMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CF
        {
            get
            {
                return this.CFField;
            }
            set
            {
                this.CFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SESSO
        {
            get
            {
                return this.SESSOField;
            }
            set
            {
                this.SESSOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CODICE_LUOGO_NASCITA
        {
            get
            {
                return this.CODICE_LUOGO_NASCITAField;
            }
            set
            {
                this.CODICE_LUOGO_NASCITAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string LUOGO_NASCITA
        {
            get
            {
                return this.LUOGO_NASCITAField;
            }
            set
            {
                this.LUOGO_NASCITAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DATA_NASCITA
        {
            get
            {
                return this.DATA_NASCITAField;
            }
            set
            {
                this.DATA_NASCITAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string EMAIL
        {
            get
            {
                return this.EMAILField;
            }
            set
            {
                this.EMAILField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string POSIZIONE_GIURIDICA
        {
            get
            {
                return this.POSIZIONE_GIURIDICAField;
            }
            set
            {
                this.POSIZIONE_GIURIDICAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string FASCIA_RETRIBUTIVA
        {
            get
            {
                return this.FASCIA_RETRIBUTIVAField;
            }
            set
            {
                this.FASCIA_RETRIBUTIVAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ID_DIPARTIMENTO
        {
            get
            {
                return this.ID_DIPARTIMENTOField;
            }
            set
            {
                this.ID_DIPARTIMENTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string DIPARTIMENTO
        {
            get
            {
                return this.DIPARTIMENTOField;
            }
            set
            {
                this.DIPARTIMENTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ID_UFFICIO
        {
            get
            {
                return this.ID_UFFICIOField;
            }
            set
            {
                this.ID_UFFICIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string UFFICIO
        {
            get
            {
                return this.UFFICIOField;
            }
            set
            {
                this.UFFICIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string ID_SERVIZIO
        {
            get
            {
                return this.ID_SERVIZIOField;
            }
            set
            {
                this.ID_SERVIZIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string SERVIZIO
        {
            get
            {
                return this.SERVIZIOField;
            }
            set
            {
                this.SERVIZIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string ANSURNAM1
        {
            get
            {
                return this.ANSURNAM1Field;
            }
            set
            {
                this.ANSURNAM1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string ANNAME1
        {
            get
            {
                return this.ANNAME1Field;
            }
            set
            {
                this.ANNAME1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string ANEMAIL1
        {
            get
            {
                return this.ANEMAIL1Field;
            }
            set
            {
                this.ANEMAIL1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string ANSURNAM2
        {
            get
            {
                return this.ANSURNAM2Field;
            }
            set
            {
                this.ANSURNAM2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string ANNAME2
        {
            get
            {
                return this.ANNAME2Field;
            }
            set
            {
                this.ANNAME2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string ANEMAIL2
        {
            get
            {
                return this.ANEMAIL2Field;
            }
            set
            {
                this.ANEMAIL2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string ANSURNAM3
        {
            get
            {
                return this.ANSURNAM3Field;
            }
            set
            {
                this.ANSURNAM3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string ANNAME3
        {
            get
            {
                return this.ANNAME3Field;
            }
            set
            {
                this.ANNAME3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string ANEMAIL3
        {
            get
            {
                return this.ANEMAIL3Field;
            }
            set
            {
                this.ANEMAIL3Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws_vqr_lavoroagile.ws.localhost/", ConfigurationName="ZucchettiAnagServiceReference.ws_vqr_lavoroagileWS")]
    public interface ws_vqr_lavoroagileWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ZucchettiAnagServiceReference.ws_vqr_lavoroagile_QueryResponse> ws_vqr_lavoroagile_QueryAsync(ZucchettiAnagServiceReference.ws_vqr_lavoroagile_Query request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ZucchettiAnagServiceReference.ws_vqr_lavoroagile_TabularQueryResponse> ws_vqr_lavoroagile_TabularQueryAsync(ZucchettiAnagServiceReference.ws_vqr_lavoroagile_TabularQuery request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ws_vqr_lavoroagile_Query
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ws_vqr_lavoroagile_Query", Namespace="http://ws_vqr_lavoroagile.ws.localhost/", Order=0)]
        public ZucchettiAnagServiceReference.ws_vqr_lavoroagile_QueryBody Body;
        
        public ws_vqr_lavoroagile_Query()
        {
        }
        
        public ws_vqr_lavoroagile_Query(ZucchettiAnagServiceReference.ws_vqr_lavoroagile_QueryBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_vqr_lavoroagile.ws.localhost/")]
    public partial class ws_vqr_lavoroagile_QueryBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string m_UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string m_Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string m_Company;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pANEMAIL;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool m_bCount;
        
        public ws_vqr_lavoroagile_QueryBody()
        {
        }
        
        public ws_vqr_lavoroagile_QueryBody(string m_UserName, string m_Password, string m_Company, string pANEMAIL, bool m_bCount)
        {
            this.m_UserName = m_UserName;
            this.m_Password = m_Password;
            this.m_Company = m_Company;
            this.pANEMAIL = pANEMAIL;
            this.m_bCount = m_bCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ws_vqr_lavoroagile_QueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ws_vqr_lavoroagile_QueryResponse", Namespace="http://ws_vqr_lavoroagile.ws.localhost/", Order=0)]
        public ZucchettiAnagServiceReference.ws_vqr_lavoroagile_QueryResponseBody Body;
        
        public ws_vqr_lavoroagile_QueryResponse()
        {
        }
        
        public ws_vqr_lavoroagile_QueryResponse(ZucchettiAnagServiceReference.ws_vqr_lavoroagile_QueryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_vqr_lavoroagile.ws.localhost/")]
    public partial class ws_vqr_lavoroagile_QueryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ws_vqr_lavoroagile_QueryResponseBody()
        {
        }
        
        public ws_vqr_lavoroagile_QueryResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ws_vqr_lavoroagile_TabularQuery
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ws_vqr_lavoroagile_TabularQuery", Namespace="http://ws_vqr_lavoroagile.ws.localhost/", Order=0)]
        public ZucchettiAnagServiceReference.ws_vqr_lavoroagile_TabularQueryBody Body;
        
        public ws_vqr_lavoroagile_TabularQuery()
        {
        }
        
        public ws_vqr_lavoroagile_TabularQuery(ZucchettiAnagServiceReference.ws_vqr_lavoroagile_TabularQueryBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_vqr_lavoroagile.ws.localhost/")]
    public partial class ws_vqr_lavoroagile_TabularQueryBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string m_UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string m_Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string m_Company;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pANEMAIL;
        
        public ws_vqr_lavoroagile_TabularQueryBody()
        {
        }
        
        public ws_vqr_lavoroagile_TabularQueryBody(string m_UserName, string m_Password, string m_Company, string pANEMAIL)
        {
            this.m_UserName = m_UserName;
            this.m_Password = m_Password;
            this.m_Company = m_Company;
            this.pANEMAIL = pANEMAIL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ws_vqr_lavoroagile_TabularQueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ws_vqr_lavoroagile_TabularQueryResponse", Namespace="http://ws_vqr_lavoroagile.ws.localhost/", Order=0)]
        public ZucchettiAnagServiceReference.ws_vqr_lavoroagile_TabularQueryResponseBody Body;
        
        public ws_vqr_lavoroagile_TabularQueryResponse()
        {
        }
        
        public ws_vqr_lavoroagile_TabularQueryResponse(ZucchettiAnagServiceReference.ws_vqr_lavoroagile_TabularQueryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws_vqr_lavoroagile.ws.localhost/")]
    public partial class ws_vqr_lavoroagile_TabularQueryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ZucchettiAnagServiceReference.ws_vqr_lavoroagile_TabularQueryResponseTable Records;
        
        public ws_vqr_lavoroagile_TabularQueryResponseBody()
        {
        }
        
        public ws_vqr_lavoroagile_TabularQueryResponseBody(ZucchettiAnagServiceReference.ws_vqr_lavoroagile_TabularQueryResponseTable Records)
        {
            this.Records = Records;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface ws_vqr_lavoroagileWSChannel : ZucchettiAnagServiceReference.ws_vqr_lavoroagileWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class ws_vqr_lavoroagileWSClient : System.ServiceModel.ClientBase<ZucchettiAnagServiceReference.ws_vqr_lavoroagileWS>, ZucchettiAnagServiceReference.ws_vqr_lavoroagileWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ws_vqr_lavoroagileWSClient() : 
                base(ws_vqr_lavoroagileWSClient.GetDefaultBinding(), ws_vqr_lavoroagileWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ws_vqr_lavoroagileWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_vqr_lavoroagileWSClient(EndpointConfiguration endpointConfiguration) : 
                base(ws_vqr_lavoroagileWSClient.GetBindingForEndpoint(endpointConfiguration), ws_vqr_lavoroagileWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_vqr_lavoroagileWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ws_vqr_lavoroagileWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_vqr_lavoroagileWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ws_vqr_lavoroagileWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ws_vqr_lavoroagileWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZucchettiAnagServiceReference.ws_vqr_lavoroagile_QueryResponse> ZucchettiAnagServiceReference.ws_vqr_lavoroagileWS.ws_vqr_lavoroagile_QueryAsync(ZucchettiAnagServiceReference.ws_vqr_lavoroagile_Query request)
        {
            return base.Channel.ws_vqr_lavoroagile_QueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZucchettiAnagServiceReference.ws_vqr_lavoroagile_QueryResponse> ws_vqr_lavoroagile_QueryAsync(string m_UserName, string m_Password, string m_Company, string pANEMAIL, bool m_bCount)
        {
            ZucchettiAnagServiceReference.ws_vqr_lavoroagile_Query inValue = new ZucchettiAnagServiceReference.ws_vqr_lavoroagile_Query();
            inValue.Body = new ZucchettiAnagServiceReference.ws_vqr_lavoroagile_QueryBody();
            inValue.Body.m_UserName = m_UserName;
            inValue.Body.m_Password = m_Password;
            inValue.Body.m_Company = m_Company;
            inValue.Body.pANEMAIL = pANEMAIL;
            inValue.Body.m_bCount = m_bCount;
            return ((ZucchettiAnagServiceReference.ws_vqr_lavoroagileWS)(this)).ws_vqr_lavoroagile_QueryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZucchettiAnagServiceReference.ws_vqr_lavoroagile_TabularQueryResponse> ZucchettiAnagServiceReference.ws_vqr_lavoroagileWS.ws_vqr_lavoroagile_TabularQueryAsync(ZucchettiAnagServiceReference.ws_vqr_lavoroagile_TabularQuery request)
        {
            return base.Channel.ws_vqr_lavoroagile_TabularQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZucchettiAnagServiceReference.ws_vqr_lavoroagile_TabularQueryResponse> ws_vqr_lavoroagile_TabularQueryAsync(string m_UserName, string m_Password, string m_Company, string pANEMAIL)
        {
            ZucchettiAnagServiceReference.ws_vqr_lavoroagile_TabularQuery inValue = new ZucchettiAnagServiceReference.ws_vqr_lavoroagile_TabularQuery();
            inValue.Body = new ZucchettiAnagServiceReference.ws_vqr_lavoroagile_TabularQueryBody();
            inValue.Body.m_UserName = m_UserName;
            inValue.Body.m_Password = m_Password;
            inValue.Body.m_Company = m_Company;
            inValue.Body.pANEMAIL = pANEMAIL;
            return ((ZucchettiAnagServiceReference.ws_vqr_lavoroagileWS)(this)).ws_vqr_lavoroagile_TabularQueryAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ws_vqr_lavoroagileWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ws_vqr_lavoroagileWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://portal.gp.pcm.it/portal/servlet/SQLDataProviderServer/ws_vqr_lavoroagile");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ws_vqr_lavoroagileWSClient.GetBindingForEndpoint(EndpointConfiguration.ws_vqr_lavoroagileWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ws_vqr_lavoroagileWSClient.GetEndpointAddress(EndpointConfiguration.ws_vqr_lavoroagileWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ws_vqr_lavoroagileWSPort,
        }
    }
}
